### PR TITLE
Cleaned up CMake file, added .gitignore and added shader compilation directly into the CMake file.  

### PR DESCRIPTION
**Pull request by Cazadorro**
Cleaned up CMake file, added .gitignore and added shader compilation directly into the CMake file.  There's now an option (default OFF) to compile the shaders via CMake, also option to manually specify the glslangvalidator path, default just uses glslangvalidator, like the bat file.

### CODE REVIEW

**Comment by DTolm** [comment]
Hello, I am not entirely convinced that shaders compilation needs to be included into cmake. Most projects keep it as a separate python script, which is what I will do later. Adding it will unnecessarily complicate cmakelists at the later stage, once I add 8k,16k shaders and double shaders, as the total number of them will be ~100. I will merge gitignore and rest of changes.

**Comment by Cazadorro** [comment]
I'll make changes, but I need some clarification on the CMake shader building. 

> Hello, I am not entirely convinced that shaders compilation needs to be included into cmake. Most projects keep it as a separate python script, which is what I will do later. Adding it will unnecessarily complicate cmakelists at the later stage, once I add 8k,16k shaders and double shaders, as the total number of them will be ~100. I will merge gitignore and rest of changes.

Most projects:
* only provide the .spv, with no compilation script, 
* use CMake/what ever build system they used.  
* use a .bat file
* use a .sh file
* do the compilation directly in code

I'm unaware of any repository that uses python to do this.

There are a lot of reasons to CMake/what ever build system you use to accomplish shader compilation as well, enough that [Sascha Willems](https://github.com/SaschaWillems/Vulkan/issues/202) has been contemplating their usage, as well as several other notable projects (the first 6 I could find in 5 minutes):

* https://github.com/jpbruyere/vkvg/blob/master/CMakeLists.txt, 
* https://github.com/nyorain/rvg/blob/master/src/shaders/meson.build, 
* https://github.com/inexorgame/vulkan-renderer/blob/master/shaders/CMakeLists.txt
* https://github.com/pumexx/pumex/blob/master/CMakeLists.txt
* https://github.com/DiligentGraphics/DiligentSamples/blob/Samples/Atmosphere/CMakeLists.txt
* https://github.com/Noxagonal/Vulkan2DRenderer/blob/master/CMakeLists.txt

The reasons why you would opt to use your build system over platform dependent script files or a 3rd party language are as follows:

* You automatically get compilation on source code change of the shaders when you change them.  This is the number one reason I do this, it is annoying to have to exit a window, go to another window, then run a script to compile my code, then go back in to your original IDE, then run your code (if you're debugging or what ever). 
* You have a platform independent way of executing shader compilation
* You have an easy method to allow users to specify their application directories for compilation or any other type of configuration from one place
* You only have to add the source file locations in one place. 
* You don't needlessly compile when there weren't any changes to be made. 
* It ultimately makes it easier for *other* people to develop the code. 
* Guaranteed to work out of the box, no external dependencies required. 

If you still want two separate scripts to do the same thing, but for different platforms, I'll be happy to remove the CMake functionality, but I'm unfortunately not willing to make a .sh file in its place.  My development setup makes it so that a hypothetical .sh and the .bat file, as currently written with out configuration for path of glslangvalidator, are not usable for me, and I don't want to be responsible for maintaining multiple duplicate/similar scripts.

**Comment by DTolm** [comment]
I am open for discussion. The python using repository is [https://github.com/LunarG/VulkanSamples](https://github.com/LunarG/VulkanSamples) (see build for android). However, I think I have an idea on how to implement this correctly now. Instead of hardcoding all the shaders names, cmake should loop over all .comp files in specified directory and subdirectories. This way we can add more shaders with no changes to CmakeLists and .spv names should be equal to their .comp counterparts either way. I think this is what have been done in the first repository you have linked - vkvg. 

By the way, Vulkan_FFT.cpp is not a part of the library - it is just an example application. The library consists only of vkFFT.h (written in C) and shaders, so the script to generate shaders has to be presented in some form independent of CmakeLists. I just didn't think on how to make this form pretty enough as there are still many things planned for the engine updates, which I want to do before.

**Comment by Cazadorro** [comment]
The method I used was by no means the best method to use in CMake, if you want an automatic scanning of .comp files and generating the appropriate dependencies of them on VkFFT, I can do that. 

>By the way, Vulkan_FFT.cpp is not a part of the library - it is just an example application. The library consists only of vkFFT.h (written in C) and shaders, so the script to generate shaders has to be presented in some form independent of CmakeLists. I just didn't think on how to make this form pretty enough as there are still many things planned for the engine updates, which I want to do before.

If I understand you correctly, this *shouldn't* be an issue, the script need not be independent of CMake even if the target it is tied to is an interface library. Creating a dependency between VkFFT and the shaders makes it so that the shaders will still attempt to compile if the source changes, this appeared to be the case on my end, I'll make sure.   If you look at the CMake command I used, the shaders were not tied to Vulkan_FFT, but VkFFT.

**Comment by DTolm** [comment]
Automatic scanning and compiling is a good way to proceed with the development until the list of shaders is finalized in some form. At that point, there will be a precompiled stable version of VkFFT which will have shaders included.

**Comment by diiigle** [comment]
This is what I ended up crafting today and I thought I'd share it with you. 
It will run over all files with `.glsl` extension and create file-level dependencies in CMake, such that the build system knows when to compile which shader. `${file}` is in the source directory, whereas `${OUTPUT_FILENAME}` will be relative to the binary directory (default `WORKING_DIRECTORY` of `add_custom_command`)
```cmake
find_program(
	GLSL_VALIDATOR
	glslangValidator
	DOC "Vulkan Shader Compiler (glslangValidator)"
	REQUIRED
)

file(GLOB files "*.glsl")
foreach(file ${files})
	get_filename_component(OUTPUT_FILENAME ${file} NAME)
	add_custom_command(
		OUTPUT ${OUTPUT_FILENAME}.spv
		COMMAND ${GLSL_VALIDATOR} -V ${file} -o ${OUTPUT_FILENAME}.spv
		COMMENT "Compiling shaders ..."
		DEPENDS ${file}
	)
	list(APPEND OUTPUT_SHADERS ${OUTPUT_FILENAME}.spv)
endforeach()

add_custom_target(compile_shaders ALL
	DEPENDS ${OUTPUT_SHADERS})
```

**Comment by DTolm** [comment]
Thanks for the input! I will test and add this with the next update. I will probably close this pull request after, since indirect shader compilation is the main outcome of it.

**Comment by DTolm** [comment]
I have added the shader directory scanning and compiling script to the CMakeLists.

**Pull request closed without merging**
