### PR TITLE
Add error string printing to VkFFT

### PR DESCRIPTION
**Pull request by sbalint98**
As far as I can tell currently there is no way to print the errors generated by VkFFT. In order to have this functionality the best approach seems to be to add a large switch statement to client code, like intended in the case of GROMACS: https://gitlab.com/gromacs/gromacs/-/merge_requests/2867/diffs#f99ad054450d6f282185a0bdeb90f35ca3a6bb41_0_74

This approach is rather fragile, and will most likely require some maintenance very soon as new errors are added to VkFFT. Would it be possible to upstream this functionality in some way?

### CODE REVIEW

**Comment by DTolm** [comment]
Hello, 
I would rather do this without additional defines like it is done here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/generated/vk_enum_string_helper.h
Yes, it will not port new errors to it, but it is not a big problem.
Best regards,
Dmitrii

**Comment by sbalint98** [comment]
Removed the macro, let me know what you think

**Review by DTolm — CHANGES_REQUESTED** [review]
You undid your previous commit here: VKFFT_ERROR_EMPRY_useCustomBluesteinPaddingPattern_arrays

**Comment by sbalint98** [comment]
rebased, should be good now

**Comment by DTolm** [comment]
I have added the missing static inline cast to not cause issues with multiple inclusions and to be in line with the rest of the function calls.

Best regards,
Dmitrii

**Pull request merged**
